role:
  旁白: "Chinese (Mandarin)_Male_Announcer"
  大雄: "Chinese (Mandarin)_ExplorativeGirl"
  哆啦A梦: "Chinese (Mandarin)_Pure-hearted_Boy"
  其他男声: "Chinese (Mandarin)_Pure-hearted_Boy"
  其他女声: "Chinese (Mandarin)_ExplorativeGirl"
  其他: "Chinese (Mandarin)_Radio_Host"