services:
  app:
    image: chengjiale150/bananalecture:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bananalecture
    ports:
      - "3574:80"
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./.env.example:/app/.env.example
      - ./storage:/app/storage
    restart: unless-stopped
